apiVersion: apps/v1
kind: Deployment
metadata:
  name: tutoring-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tutoring-app
  template:
    metadata:
      labels:
        app: tutoring-app
    spec:
      containers:
      - name: tutoring-app
        image: your-docker-username/tutoring-app:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: tutoring-app-service
spec:
  type: LoadBalancer
  selector:
    app: tutoring-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080

